apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source: 
<<<<<<< HEAD
    repoURL: https://github.com/CloudknightOps/Argocd-test-repo.git
=======
    repoURL: https://github.com/CloudknightOps/Argocd-test-repo.gi
>>>>>>> a29e31caf1662ba50dac375db49c615a4282d3cf
    targetRevision: HEAD
    path: deploy
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true 
      prune: true